version: '3.6'

services:
  # mongo
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - 'mongo:/data/db'

  server:
    depends_on:
    - 'mongo'
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: server
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}

volumes:
  mongo:
