name: deploy main

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          # go-version: 1.19
          # get go version by go.mod file
          go-version-file: 'go.mod'
          # cache dependencies
          cache: true

      - name: clean / download / tidy
        uses: actions/setup-go@v3
        run: |
          go mod clean
          go mod download
          go mod tidy

      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: build project
        uses: actions/setup-go@v3
        run: go build .\cmd\startup\

      - name: test
        uses: actions/setup-go@v3
        run: ginkgo -r
