name: deploy main

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          # go-version: 1.19
          # get go version by go.mod file
          go-version-file: 'go.mod'
          # cache dependencies
          cache: true

      - name: mod
        run: |
          go clean
          go mod download
          go mod tidy

      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: vet
        run: go vet ./...

      - name: build
        run: go build ./cmd/startup/

      - name: test
        run: |
          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo@latest
          ginkgo -r -p

    # env
    env:
      STAGE: prod
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

