name: deploy main

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build-release:
    runs-on: ubuntu-latest

    environment: Production

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          # go-version: 1.19
          # get go version by go.mod file
          go-version-file: 'go.mod'
          # cache dependencies
          cache: true

      - name: go mod
        run: |
          go clean
          go mod download
          go mod tidy

      - name: go lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: go lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: go vet
        run: go vet ./...

      - name: go build
        run: go build ./cmd/startup/

      - name: go test
        run: |
          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo@latest
          ginkgo -r -p

      #  node steps
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: npm install
        run: npm install --frozen-lockfile

      - name: npm lint
        run: npm run lint

      - name: sst deploy
        run: |
          set -euxo pipefail
          npx sst deploy --stage prod

env:
  STAGE: prod
  MONGO_URI: ${{ secrets.MONGO_URI }}
  DATABASE: ${{ secrets.DATABASE }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
